var express = require('express');
var router = express.Router();
var adminControllers = require(process.cwd() + '/controllers/adminController');
router.route('/').get(adminControllers.bootstrap,adminControllers.login);
router.route('/loginsubmit').post(adminControllers.loginsubmit);
router.route('/dashbaord').get(adminControllers.bootstrap,adminControllers.dashbaord);
router.route('/logout').get(adminControllers.logout);
router.route('/category_list').get(adminControllers.bootstrap,adminControllers.category_list);
router.route('/addCategory').get(adminControllers.bootstrap,adminControllers.addCategory);
router.route('/add_category').post(adminControllers.bootstrap,adminControllers.add_category);
router.route('/delete_category/:objectId').get(adminControllers.delete_category);
router.route('/slider_list').get(adminControllers.bootstrap,adminControllers.slider_list);
router.route('/addSlider').get(adminControllers.addSlider);
router.route('/add_slider').post(adminControllers.add_slider);
router.route('/delete_slider/:objectId').get(adminControllers.delete_slider);
router.route('/product_list').get(adminControllers.bootstrap,adminControllers.product_list);
router.route('/addProduct').get(adminControllers.bootstrap,adminControllers.addProduct);
router.route('/add_product').post(adminControllers.bootstrap,adminControllers.add_product);
module.exports = router;